
language: node_js

node_js:
  - "node"

cache:
  - node_modules

branches:
  only:
    - master

before_install:
  - npm i -g makeshift
  - makeshift -s @oddbit -r https://registry.npmjs.org

install:
  - npm install

deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_AUTH_TOKEN