
language: node_js

node_js:
  - "node"

cache:
  - node_modules

branches:
  only:
    - master

before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
  - npm config set @oddbit:registry https://registry.npmjs.org/

install:
  - npm install

script:
  - npm publish --access=public
